### ISSUE TITLE
Publish on crates.io

### ISSUE THREAD

**Issue by azizkayumov** [aicers/srtree#22]
Follow the guidelines here: https://doc.rust-lang.org/cargo/reference/publishing.html

**Comment by azizkayumov** [comment]
@msk Please let me know if I can publish beta from my own account on crates.io or Aicer's Cargo account.

**Comment by msk** [comment]
To @azizkayumov: Go ahead and publish the crate.

To @syncpark, @sehkone: Please designate someone else as the co-owner of this crate on crates.io, and ask @azizkayumov to add them as additional owners. We need at least two owners per package in case one of the owners can no longer maintain the crate.

**Comment by syncpark** [comment]
@azizkayumov Add me as additional owner. My github account is `syncpark@github.com`, and my enterprise address is `dkpark@petabi.com`. If you need another information, please let me know.

**Comment by azizkayumov** [comment]
This is awesome! Thank for your help. I published the crate here: https://crates.io/crates/srtree. Will be updating the docs soon.

**Comment by azizkayumov** [comment]
@syncpark I tried with both of your emails and your Github username to give ownership access on crates.io. Somehow, it couldn't find any account:
<img width="411" alt="Screen Shot 2023-05-17 at 5 07 28 AM" src="https://github.com/aicers/srtree/assets/14273342/e4dbd643-ca0c-4a1d-b97a-08edd568539f">

Please let me know your username for crates.io.

**Comment by syncpark** [comment]
My GitHub account is `syncpark` but maybe it’s not allowed as email address. Instead, please use the ***@***.*** ***@***.***>` address.

**Comment by azizkayumov** [comment]
@syncpark Thank you for clarification. I think your Github account should be connected to crates.io to make it work. Please login with your Github account on [crates.io](https://crates.io/) (so that the website knows your Github account).

**Comment by syncpark** [comment]
I just logged in to crates.io <http://crates.io/> with Github account. Is there anything else to do?

**Comment by syncpark** [comment]
Ok I just found the “srtree 0.1.0” is registered in my dashboard. Thanks

**Comment by azizkayumov** [comment]
Thank you for quick reply. Yes, crates.io shows that it has sent an invitation email to you, please accept the ownership invite.

**Comment by azizkayumov** [comment]
Closing as completed, thank you for your help!

**Comment by syncpark** [comment]
I’ve already accepted the invitation.

**Comment by azizkayumov** [comment]
Yes, now it shows your username on crates.io as well. Thank you~
