### ISSUE TITLE
Repository settings

### ISSUE THREAD

**Issue by azizkayumov** [aicers/srtree#30]
<img width="254" alt="Screen Shot 2023-05-18 at 10 07 40 AM" src="https://github.com/aicers/srtree/assets/14273342/afbe66f4-b4c7-4757-b168-d7a6783910b7">

@msk I couldn't change the repository's "About" section here (and repository "Settings" section is hidden), let me know if you can enable the edit settings for my username.

**Comment by msk** [comment]
Changed the permission settings for you. Should work now.
